// Generated by scripts/generate_openapi_types.py. Do not edit manually.

export type AuthResponse = {
  user: UserResponse;
  csrfToken: string;
};

export type HTTPValidationError = {
  detail?: ValidationError[];
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type MeResponse = {
  user: UserResponse;
};

export type RegisterRequest = {
  email: string;
  password: string;
  displayName: string;
};

export type TripCreateRequest = {
  title: string;
  description?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  timezoneId?: string;
  dayCutoffHour?: number;
};

export type TripResponse = {
  id: string;
  title: string;
  description: string | null;
  startDate: string | null;
  endDate: string | null;
  timezoneId: string;
  dayCutoffHour: number;
  status: string;
  visibility: string;
  role: string;
  createdAt: string;
  updatedAt: string;
};

export type TripUpdateRequest = {
  title?: string | null;
  description?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  timezoneId?: string | null;
  dayCutoffHour?: number | null;
  status?: string | null;
  visibility?: string | null;
};

export type TripsListResponse = {
  trips: TripResponse[];
};

export type UserResponse = {
  id: string;
  email: string;
  display_name: string;
};

export type ValidationError = {
  loc: (string | number)[];
  msg: string;
  type: string;
};
