// Generated by scripts/generate_openapi_types.py. Do not edit manually.

export type AdminUserResponse = {
  id: string;
  email: string;
  displayName: string;
  tier: TierResponse;
  tripCount: number;
  photoCount: number;
  monthlyUploadedBytes: number;
};

export type AdminUsersResponse = {
  users: AdminUserResponse[];
};

export type AreaVisitResponse = {
  id: string;
  tripId: string;
  dayId: string;
  reconstructionRunId: string;
  sortOrder: number;
  title?: string | null;
  startsAt?: string | null;
  endsAt?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  confidence?: number | null;
  source: string;
  algorithmVersion: string;
  userLocked: boolean;
  bounds: Record<string, unknown>;
  diagnostics: Record<string, unknown>;
  stops: AreaVisitStopResponse[];
};

export type AreaVisitStopResponse = {
  id: string;
  position: number;
  title?: string | null;
  startsAt: string;
  endsAt: string;
  placeName?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  membershipSource?: string | null;
  membershipConfidence?: number | null;
  membershipSortOrder?: number | null;
  membershipUserLocked?: boolean | null;
};

export type AreaVisitsResponse = {
  tripId: string;
  dayId: string;
  sourceReconstructionRunId?: string | null;
  areas: AreaVisitResponse[];
  standaloneStops: AreaVisitStopResponse[];
};

export type AuthResponse = {
  user: UserResponse;
  csrfToken: string;
};

export type BlobRefResponse = {
  storeAlias: string;
  objectKey: string;
  checksumAlgorithm?: string | null;
  checksum?: string | null;
  sizeBytes?: number | null;
  contentType?: string | null;
};

export type CompleteUploadFileResponse = {
  file: UploadFileResponse;
};

export type EditOperationRequest = {
  operationType: string;
  payload?: Record<string, unknown>;
  reviewItemId?: string | null;
  expectedUpdatedAt?: string | null;
};

export type EditOperationResponse = {
  id: string;
  operationType: string;
  status: string;
  targetType?: string | null;
  targetId?: string | null;
  beforeValues: Record<string, unknown>;
  afterValues: Record<string, unknown>;
  createdAt: string;
};

export type GuestMemberResponse = {
  id: string;
  tripId: string;
  displayName: string;
  role: string;
  csrfToken: string;
};

export type HTTPValidationError = {
  detail?: ValidationError[];
};

export type InvitationAcceptRequest = {
  displayName?: string | null;
};

export type InvitationCreateRequest = {
  expiresInSeconds?: number | null;
};

export type InvitationPreviewResponse = {
  tripId: string;
  title: string;
  role: string;
  expiresAt: string;
  status: string;
};

export type InvitationResponse = {
  id: string;
  tripId: string;
  role: string;
  status: string;
  expiresAt: string;
  useCount: number;
  maxUses: number;
  revokedAt?: string | null;
  acceptedAt?: string | null;
  inviteUrl?: string | null;
};

export type InvitationsListResponse = {
  invitations: InvitationResponse[];
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type MeResponse = {
  user: UserResponse;
};

export type MediaAssetResponse = {
  id: string;
  assetType: string;
  width: number | null;
  height: number | null;
  mimeType: string;
  downloadUrl?: string | null;
};

export type MediaItemResponse = {
  id: string;
  filename: string | null;
  processingState: string;
  errorMessage?: string | null;
  originalRetentionState: string;
  originalDeletedAt?: string | null;
  visibility: string;
  includeInStory: boolean;
  canUpdateVisibility: boolean;
  capturedAt?: string | null;
  capturedAtLocal?: string | null;
  gpsPresent: boolean;
  latitude?: number | null;
  longitude?: number | null;
  width?: number | null;
  height?: number | null;
  contributor: string;
  contributorMemberId: string;
  thumbnail?: MediaAssetResponse | null;
  preview?: MediaAssetResponse | null;
  similarityGroupId?: string | null;
  similarityGroupCount?: number;
  similarityGroupType?: string | null;
  isSimilarityRepresentative?: boolean;
  representativeMediaItemId?: string | null;
};

export type MediaListResponse = {
  media: MediaItemResponse[];
};

export type MediaUpdateRequest = {
  visibility?: string | null;
  includeInStory?: boolean | null;
  deleted?: boolean | null;
};

export type MemberResponse = {
  id: string;
  displayName: string;
  role: string;
  joinedAt: string;
  removedAt?: string | null;
  isGuest: boolean;
};

export type MemberRosterResponse = {
  members: MemberResponse[];
};

export type PublicStoryResponse = {
  version: StoryVersionResponse;
  story: ReconstructionResponse;
  trip: Record<string, unknown>;
  participants: Record<string, unknown>[];
  areaVisitsByDay?: Record<string, unknown>;
};

export type PublicationResponse = {
  version: StoryVersionResponse;
  shareLink: ShareLinkResponse;
};

export type PublicationsListResponse = {
  versions: StoryVersionResponse[];
  shareLinks: ShareLinkResponse[];
};

export type ReconstructionDayResponse = {
  id: string;
  date: string;
  position: number;
  title?: string | null;
  note?: string | null;
  stops: ReconstructionStopResponse[];
  legs?: ReconstructionLegResponse[];
};

export type ReconstructionLegResponse = {
  id: string;
  fromStopId: string;
  toStopId: string;
  routeSource: string;
  isForked?: boolean;
  geometry?: Record<string, unknown> | null;
};

export type ReconstructionMediaResponse = {
  id: string;
  filename?: string | null;
  capturedAt?: string | null;
  capturedAtLocal?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  contributorMemberId: string;
  contributor: string;
  thumbnailUrl?: string | null;
  previewUrl?: string | null;
};

export type ReconstructionMomentResponse = {
  id: string;
  position: number;
  title?: string | null;
  startsAt: string;
  endsAt: string;
  startsAtLocal?: string | null;
  endsAtLocal?: string | null;
  mediaCount: number;
  contributorCount: number;
  media: ReconstructionMediaResponse[];
};

export type ReconstructionResponse = {
  latestRun?: ReconstructionRunResponse | null;
  days: ReconstructionDayResponse[];
  reviewItems: ReviewItemResponse[];
  storyUpdate: StoryUpdateStatusResponse;
};

export type ReconstructionRunResponse = {
  id: string;
  state: string;
  algorithmVersion: string;
  summary: Record<string, unknown>;
  startedAt: string;
  finishedAt?: string | null;
};

export type ReconstructionStopResponse = {
  id: string;
  position: number;
  displayPosition?: string | null;
  title?: string | null;
  note?: string | null;
  startsAt: string;
  endsAt: string;
  startsAtLocal?: string | null;
  endsAtLocal?: string | null;
  placeName?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  mediaCount: number;
  contributorCount: number;
  moments: ReconstructionMomentResponse[];
};

export type RegisterRequest = {
  email: string;
  password: string;
  displayName: string;
};

export type ReviewItemResponse = {
  id: string;
  itemType: string;
  severity: string;
  confidence?: number | null;
  targetType?: string | null;
  targetId?: string | null;
  targetRefs: Record<string, unknown>;
  payload: Record<string, unknown>;
  status: string;
  message: string;
  mediaItemId?: string | null;
  resolution?: string | null;
  resolvedBy?: string | null;
  resolvedAt?: string | null;
};

export type ShareLinkResponse = {
  id: string;
  tripId: string;
  storyVersionId?: string | null;
  status: string;
  expiresAt?: string | null;
  revokedAt?: string | null;
  shareUrl?: string | null;
  latestStoryUrl?: string | null;
  versionStoryUrl?: string | null;
};

export type SimilarityGroupResponse = {
  id: string;
  groupType: string;
  representativeMediaItemId: string | null;
  memberCount: number;
  reason: string;
  confidence?: number | null;
  members: SimilarityMemberResponse[];
};

export type SimilarityGroupsResponse = {
  groups: SimilarityGroupResponse[];
};

export type SimilarityMemberResponse = {
  mediaItemId: string;
  filename?: string | null;
  contributor: string;
  isRepresentative: boolean;
  technicalScore?: number | null;
  similarityScore?: number | null;
  signals: Record<string, unknown>;
};

export type StoryPhotoProjectionPhotoResponse = {
  id: string;
  filename?: string | null;
  capturedAt?: string | null;
  capturedAtLocal?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  contributorMemberId: string;
  contributor: string;
  thumbnailAssetId?: string | null;
  previewAssetId?: string | null;
  thumbnailUrl?: string | null;
  previewUrl?: string | null;
};

export type StoryPhotoProjectionResponse = {
  tripId: string;
  dayId?: string | null;
  stopId?: string | null;
  sourceReconstructionRunId: string;
  schemaVersion: number;
  stops: StoryPhotoProjectionStopResponse[];
};

export type StoryPhotoProjectionStopResponse = {
  id: string;
  dayId: string;
  position: number;
  displayPosition?: string | null;
  title?: string | null;
  placeName?: string | null;
  photos: StoryPhotoProjectionPhotoResponse[];
};

export type StoryUpdateStatusResponse = {
  needsUpdate: boolean;
  unassignedReadyMediaCount: number;
  readyMediaCount: number;
  storyMediaCount: number;
};

export type StoryVersionResponse = {
  id: string;
  tripId: string;
  versionNumber: number;
  state: string;
  title: string;
  publishedAt?: string | null;
  errorMessage?: string | null;
};

export type TierCreateRequest = {
  slug: string;
  name: string;
  maxTripsPerUser?: number | null;
  maxFilesPerTrip?: number | null;
  monthlyUploadBytes: number;
};

export type TierListResponse = {
  tiers: TierResponse[];
};

export type TierResponse = {
  id: string;
  slug: string;
  name: string;
  maxTripsPerUser: number | null;
  maxFilesPerTrip: number | null;
  monthlyUploadBytes: number;
  isActive: boolean;
};

export type TripCreateRequest = {
  title: string;
  description?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  timezoneId?: string;
  dayCutoffHour?: number;
};

export type TripMapBoundsResponse = {
  minLatitude: number;
  minLongitude: number;
  maxLatitude: number;
  maxLongitude: number;
};

export type TripMapPointResponse = {
  id: string;
  tripId: string;
  mediaItemId: string;
  capturedAt?: string | null;
  date?: string | null;
  latitude: number;
  longitude: number;
  source: string;
  confidence?: number | null;
  filename?: string | null;
  thumbnailUrl?: string | null;
};

export type TripMapTripResponse = {
  id: string;
  title: string;
  startDate?: string | null;
  endDate?: string | null;
  timezoneId: string;
  role: string;
  memberId: string;
  pointCount: number;
  firstCapturedAt?: string | null;
  lastCapturedAt?: string | null;
  bounds: TripMapBoundsResponse;
  representativeMediaItemId: string;
  representativeThumbnailUrl?: string | null;
};

export type TripQuotaResponse = {
  maxTripsPerUser: number | null;
  ownedTripCount: number;
};

export type TripResponse = {
  id: string;
  title: string;
  description: string | null;
  startDate: string | null;
  endDate: string | null;
  timezoneId: string;
  dayCutoffHour: number;
  status: string;
  visibility: string;
  role: string;
  memberId: string;
  createdAt: string;
  updatedAt: string;
};

export type TripUpdateRequest = {
  title?: string | null;
  description?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  timezoneId?: string | null;
  dayCutoffHour?: number | null;
  status?: string | null;
  visibility?: string | null;
};

export type TripsListResponse = {
  trips: TripResponse[];
  quota: TripQuotaResponse;
};

export type TripsMapPointsResponse = {
  trips: TripMapTripResponse[];
  points: TripMapPointResponse[];
  startDate?: string | null;
  endDate?: string | null;
};

export type UploadFileRegisterRequest = {
  filename: string;
  byteSize: number;
  mimeType: string;
};

export type UploadFileResponse = {
  id: string;
  state: string;
  filename: string | null;
  byteSize: number | null;
  mimeType: string | null;
  storeAlias: string;
  objectKey: string;
  sha256: string | null;
  mediaItemId?: string | null;
  errorMessage?: string | null;
  grant?: UploadGrantResponse | null;
};

export type UploadGrantResponse = {
  blobRef: BlobRefResponse;
  method: string;
  url: string;
  headers: Record<string, unknown>;
  expiresAt: string;
  maxSizeBytes: number;
  contentType?: string | null;
};

export type UploadQuotaResponse = {
  maxFilesPerTrip: number | null;
  monthlyUploadBytes: number;
  monthlyUploadedBytes: number;
  reservedFileCount: number;
  remainingFileCount: number | null;
};

export type UploadSessionCreateRequest = {
  files: UploadFileRegisterRequest[];
};

export type UploadSessionResponse = {
  id: string;
  tripId: string;
  state: string;
  declaredFileCount: number | null;
  declaredTotalBytes: number | null;
  files: UploadFileResponse[];
  limits: Record<string, unknown>;
  quota: UploadQuotaResponse;
};

export type UploadSessionsListResponse = {
  uploadSessions: UploadSessionResponse[];
  quota: UploadQuotaResponse;
};

export type UserResponse = {
  id: string;
  email: string;
  display_name: string;
};

export type UserTierResponse = {
  userId: string;
  email: string;
  tier: TierResponse;
};

export type ValidationError = {
  loc: (string | number)[];
  msg: string;
  type: string;
};
