from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
BACKEND_SRC = REPO_ROOT / "services" / "backend" / "src"
OUTPUT = REPO_ROOT / "apps" / "web" / "app" / "api-types.ts"

sys.path.insert(0, str(BACKEND_SRC))

from tripweave.entrypoints.api.main import create_app  # noqa: E402


def type_name(name: str) -> str:
    return name.replace("-", "_")


def render_schema(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return type_name(str(schema["$ref"]).rsplit("/", 1)[-1])
    if "anyOf" in schema:
        return " | ".join(render_schema(item) for item in schema["anyOf"])
    if "allOf" in schema:
        return " & ".join(render_schema(item) for item in schema["allOf"])

    schema_type = schema.get("type")
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "array":
        item_type = render_schema(schema.get("items", {}))
        if " | " in item_type or "\n" in item_type:
            return f"({item_type})[]"
        return f"{item_type}[]"
    if schema_type == "null":
        return "null"
    if schema_type == "object":
        properties = schema.get("properties", {})
        if not properties:
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        lines = ["{"]
        for prop_name, prop_schema in properties.items():
            optional = "" if prop_name in required else "?"
            lines.append(f"  {prop_name}{optional}: {render_schema(prop_schema)};")
        lines.append("}")
        return "\n".join(lines)
    return "unknown"


def render_component(name: str, schema: dict[str, Any]) -> str:
    rendered = render_schema(schema)
    return f"export type {type_name(name)} = {rendered};"


def main() -> None:
    schema = create_app().openapi()
    components = schema.get("components", {}).get("schemas", {})
    lines = [
        "// Generated by scripts/generate_openapi_types.py. Do not edit manually.",
        "",
    ]
    for name in sorted(components):
        lines.append(render_component(name, components[name]))
        lines.append("")
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
